### ISSUE TITLE
Request to add a homebrew

### ISSUE THREAD

**Issue by AlyxFYI** [RiiConnect24/UTag#11]
I am the project manager of Portal: Wii U Edition and I would like to know if it is possible to add a cover on the site and an icon on the Rich Presence. The product code is **WUP-P-PWUE** and the title id is **000500001026F300**. I give you the pictures.
![Portal-Cover](https://github.com/RiiConnect24/UTag/assets/50267518/1390b2b2-96ba-4713-b89b-be1e73e75575)
![Portal-Icon](https://github.com/RiiConnect24/UTag/assets/50267518/78ec7152-d14a-4c2c-8df5-905a5c2b679f)

**Comment by Brawl345** [comment]
You are looking for https://github.com/RiiConnect24/RiiTag-Next/issues and https://github.com/RiiConnect24/RiiTag-RPC

Also note that homebrews in WUHB format are not supported and won't send their TitleID when using UTag.

**Comment by AlyxFYI** [comment]
The project is not in WUHB but in WUP and can be installed like an official game so there's no differences with an official game
