### ISSUE TITLE
Why did you randomly stop supporting Tiramisu?

### ISSUE THREAD

**Issue by SwirlyStone5877** [RiiConnect24/UTag#12]
Aroma will not work with my Wii U and I'm stuck with a very old version of UTag now. I'm wondering, why the sudden change?

**Comment by Brawl345** [comment]
There is no plugin system for Tiramisu. The one that is out there is a broken outdated POS and the dev himself recommends to not use it & Tiramisu. I have never supported Tiramisu - in fact my first PR was porting it to the actual plugin system used by Aroma a year ago ;) Aroma works with every Wii U - what error do you get during installation?

**Comment by SwirlyStone5877** [comment]
Oh.

**Comment by SwirlyStone5877** [comment]
Just now realizing you asked for an error. There wasn't even an error. Just a black screen.

EDIT: turns out a file was corrupted lmao

**Comment by Brawl345** [comment]
Better ask in a forum like GBATemp or the Aroma discord for help and saying step by step what you did & at what step you get the error.
