### ISSUE TITLE
Utag crashes a game

### ISSUE THREAD

**Issue by ResidentNintendoNerd** [RiiConnect24/UTag#2]
When pressing the HOME button in "Mario & Sonic at the Sochi 2014 Winter Olympic Games" (Afaik this does not happen with any other game) the game crashes with the annoying "BEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEP" sound and I can confirm this does not happen when I do not apply patches or launch the game normally too.

**Comment by 2secslater** [comment]
Hi,

Can you try to launch the Wii U Plugin Loader without enabling any plugins, and try to launch the game and see if that behaviour persists?

**Comment by ResidentNintendoNerd** [comment]
> I can confirm this does not happen when I do not apply patches or launch the game normally too.

I already mentioned this in my original post.

**Comment by Brawl345** [comment]
I will close this for now since there is a rewritten version which should not cause any problems. Feel free to reopen it if you encounter the same problem with Aroma and the new version.
