### ISSUE TITLE
Does not work with discs

### ISSUE THREAD

**Issue by Brawl345** [RiiConnect24/UTag#6]
Seems like `MCP_RightCheckLaunchable` is not called on disc games. Maybe better to hook into `ACPCheckTitleLaunchByTitleListTypeEx`, see https://github.com/wiiu-env/homebrew_on_menu_plugin/blob/b10a28815033e8c9211dc208eec263666b9ac863/src/main.cpp#L469-L491

**Comment by ResidentNintendoNerd** [comment]
Any updates? Been using my Wii U more recently and since I don't have a lot of free memory space, I have to keep my games on disc

**Comment by Brawl345** [comment]
Currently not planning on working on this, sorry!

**Comment by Brawl345** [comment]
Sorry it took so long. Please test: https://github.com/RiiConnect24/UTag/releases/tag/UTag-20230328-174117

**Comment by ResidentNintendoNerd** [comment]
Sorry for the late reply lol, it does work for me, just tested with MK8

**Comment by Brawl345** [comment]
Thanks! https://github.com/RiiConnect24/UTag/releases/tag/v2.2.0
