### ISSUE TITLE
Not working on Aroma + Tiramisu

### ISSUE THREAD

**Issue by Andrew-J-Larson** [RiiConnect24/UTag#7]
I notice that the UTag install on Open Shop Channel installs to `sdcard://wiiu/plugins/...` instead of going to the right environment to install the plugin (`sdcard://wiiu/environments/[ENVIRONMENT]/plugins/...`).

Additionally, even when placed in the right spot for Tiramisu (I believe that's `sdcard://wiiu/environments/tiramisu/plugins/...`), it doesn't seem to load Utag at all (was Tiramisu support outright removed?). However, I also seemed to not be able to get it to work for Aroma either, also manually installed to the correct plugin location (`sdcard://wiiu/environments/aroma/plugins/...`). UTag.txt is at the root of the drive too.

I have the latest versions of Aroma, Tiramisu, the plugin loader (https://github.com/wiiu-env/WiiUPluginLoaderBackend), and the Utag plugin. Not sure what I'm doing wrong. (I do know my Rii-Tag is working though, as it does update my games when I hop into USB Loader GX on my vWii).

**Comment by Andrew-J-Larson** [comment]
Okay, I think I know what was wrong for Aroma (utag.txt needs to be inside of wiiu folder where as the previous versions for Tiramisu wanted it at the root of the sdcard).

That should probably be noted somewhere.

In any case, maybe the Open Shop Channel should have the older Tiramisu install on there with mentions to the old plugin loader so people can still set it up on Tiramisu.

**Comment by Brawl345** [comment]
The new version does not work on Aroma and I recommend setting up Aroma. There will be no updates to the older version. 

>That should probably be noted somewhere.

It's in the Readme.

> maybe the Open Shop Channel should have the older Tiramisu install on there

Please open an issue there, I have no control over this.
