### ISSUE TITLE
Wii games dont show up

### ISSUE THREAD

**Issue by what-coder** [RiiConnect24/UTag#8]
Wii games wont show up im on aroma

**Comment by Brawl345** [comment]
Please specify exactly what you did, what you have installed, which game you tested, which VC injector you used, etc.

**Comment by what-coder** [comment]
No, i started a wii disc from vwii

**Comment by Brawl345** [comment]
That won't work because Aroma plugins are not loaded there. Use a USB loader with RiiTag support: https://wii.guide/riitag

**Comment by what-coder** [comment]
Thanks
